package com.ehrms.deptenq.constants;

public enum ProposalState {

	NEW,
	APPROVED,
	REJECTED,
	PROVISIONAL,
	FINALIZE,
	PENDING, NOT_APPROVED,APPROVED_16B,REJECTED_16B,
	APPROVED_DPC,REJECTED_DPC,APPROVED_CMCOMMITTEE,REJECTED_CMCOMMITTEE,
	APPROVED_CSB,REJECTED_CSB,APPROVED_GAD,REJECTED_GAD,
	PROCESSING_POSTING,POSTING_COMPLETE,POSTING_GRANTED,
	POSTING_REJECTED,FILE_PROCESSED,
	WAITING,
	CLOSED
}
